DELETE FROM mysql.user WHERE User="godb";
DROP DATABASE IF EXISTS godb;
CREATE DATABASE godb DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON godb.* TO godb@'localhost' IDENTIFIED BY 'go123';
GRANT ALL PRIVILEGES ON godb.* TO godb@'127.0.0.1' IDENTIFIED BY 'go123';
GRANT ALL PRIVILEGES ON godb.* TO godb@'%' IDENTIFIED BY 'go123';

